name: Keep Spaces Awake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Crypto Gex
        run: curl -I https://lohithmahesh-market-agn.hf.space/
